name: Deployment
on:
  push:
    branches: [ master ]  # Triggers on pushes to 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: '12.x'  # Consider using a newer version if possible

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Sync
      env:
        DEPLOY_SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
        REMOTE_HOST: ${{ secrets.DEPLOY_SSH_HOST }}
        REMOTE_PORT: ${{ secrets.DEPLOY_SSH_PORT }}
        REMOTE_USER: ${{ secrets.DEPLOY_SSH_USER }}
        DEPLOY_SSH_PATH: ${{ secrets.DEPLOY_SSH_PATH }}  # Use the variable from secrets
      run: |
        echo "${{ env.DEPLOY_SSH_KEY }}" > deploy_key
        chmod 600 deploy_key
        rsync -chavz --delete -e "ssh -i ./deploy_key -p ${{ env.REMOTE_PORT }} -o StrictHostKeyChecking=no" \
          --exclude /deploy_key \
          --exclude /.git/ \
          --exclude /.github/ \
          --exclude /node_modules/ \
          wp/wp-content/themes/barkbites/ ${{ env.REMOTE_USER }}@${{ env.REMOTE_HOST }}:${{ env.DEPLOY_SSH_PATH }}

    - name: Clear SG Cache
      env:
        DEPLOY_SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
        REMOTE_HOST: ${{ secrets.DEPLOY_SSH_HOST }}
        REMOTE_PORT: ${{ secrets.DEPLOY_SSH_PORT }}
        REMOTE_USER: ${{ secrets.DEPLOY_SSH_USER }}
        DEPLOY_WP_PATH: ${{ secrets.DEPLOY_WP_PATH }}
      run: |
        ssh -i deploy_key -p ${{ env.REMOTE_PORT }} -o StrictHostKeyChecking=no ${{ env.REMOTE_USER }}@${{ env.REMOTE_HOST }} "cd ${{ env.DEPLOY_SSH_WP_PATH }} && wp sg purge"
